"""crear_tabla_tipos_unidad

Revision ID: 1ebdb70ac0e5
Revises: 1f3e2b0c4ec3
Create Date: 2026-07-17 00:10:37.202459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebdb70ac0e5'
down_revision: Union[str, None] = '1f3e2b0c4ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
