"""crear_tabla_condominios

Revision ID: 1f3e2b0c4ec3
Revises: 73a856c5b059
Create Date: 2026-07-17 00:07:14.886679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3e2b0c4ec3'
down_revision: Union[str, None] = '73a856c5b059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
