"""crear_tabla_tipos_cuenta_bancaria

Revision ID: 37e7d6651198
Revises: 5b156e6057af
Create Date: 2026-07-17 00:17:05.031437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e7d6651198'
down_revision: Union[str, None] = '5b156e6057af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
