"""crear_tabla_bancos

Revision ID: 5b156e6057af
Revises: 1ebdb70ac0e5
Create Date: 2026-07-17 00:14:05.584008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b156e6057af'
down_revision: Union[str, None] = '1ebdb70ac0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
