"""crear_tabla_categorias_gasto

Revision ID: 5b506ee7a6d0
Revises: 59430a93ede6
Create Date: 2026-07-17 00:30:53.061292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b506ee7a6d0'
down_revision: Union[str, None] = '59430a93ede6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
